import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "../../../globals.css";

import Header from "./_components/header";
import Sidebar from "./_components/sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// const sans = GeistSans({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
// });

// const mono = GeistMono({
//   subsets: ["latin"],
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
          <Sidebar />
          <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
            <Header />
            <main className="p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}

// ${mono.variable}
// ${sans.variable}
