import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "../../../globals.css";
import { redirect } from "next/navigation";
import { getUser } from "@/lib/auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// const sans = GeistSans({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
// });

// const mono = GeistMono({
//   subsets: ["latin"],
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "Sign-In",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session, user } = await getUser();

  if (session && user.role === "superadmin") {
    return redirect("/dashboard");
  }

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>{children}</body>
    </html>
  );
}

// ${mono.variable}
